label fin3:
    r "Regarde Athenais le cable !!"
    a " On a reussi F4"
    r "Oui on a reu .. .. . Argh . .  .. . "
    a " Qui a-t-il F4 ? ça va ?"
    r " Je bzzt ..@!!%**£$$d$$z$d$zdù!:$$d$zdù$*éé"
    r "0111 0100 1000 1010 1110 1101 0110 1010"
    a "Que se passe t'il F4 ? tu me fait peur"
    r "Unité F4-112R prêt au service"
    a " ???? "
    r " Un humain, protocle d'élimation engager"
    a "Quesque ?!!"
    "* Sing Shing*"
    a "DEAD"
    "GAME OVER"
